#Description: FreeRTOS heap 4; user_visible: False
include_guard(GLOBAL)
message("middleware_freertos-kernel_heap_4 component is included.")

target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/portable/MemMang/heap_4.c
)

target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
)

#OR Logic component
if(${MCUX_DEVICE} STREQUAL "MIMXRT1166_cm4")
    include(middleware_freertos-kernel_MIMXRT1166_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1166_cm7")
    include(middleware_freertos-kernel_MIMXRT1166_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5506CPXXXX")
    include(middleware_freertos-kernel_LPC5506CPXXXX)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1052")
    include(middleware_freertos-kernel_MIMXRT1052)
endif()
if(${MCUX_DEVICE} STREQUAL "MK22F12810")
    include(middleware_freertos-kernel_MK22F51212)
endif()
if(${MCUX_DEVICE} STREQUAL "MKV10Z1287")
    include(middleware_freertos-kernel_MKV11Z7)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT633S_cm33")
    include(middleware_freertos-kernel_MIMXRT685S_cm33)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1064")
    include(middleware_freertos-kernel_MIMXRT1064)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5526")
    include(middleware_freertos-kernel_LPC55S28)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5504CPXXXX")
    include(middleware_freertos-kernel_LPC5506CPXXXX)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54607")
    include(middleware_freertos-kernel_LPC54628)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S016")
    include(middleware_freertos-kernel_LPC54S018)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54606")
    include(middleware_freertos-kernel_LPC54628)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54616")
    include(middleware_freertos-kernel_LPC54628)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MN5")
    include(middleware_freertos-kernel_MIMX8MN6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MN4")
    include(middleware_freertos-kernel_MIMX8MN6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MQ6")
    include(middleware_freertos-kernel_MIMX8MQ6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MM6")
    include(middleware_freertos-kernel_MIMX8MM6)
endif()
if(${MCUX_DEVICE} STREQUAL "MKE15Z7")
    include(middleware_freertos-kernel_MKE15Z7)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S04")
    include(middleware_freertos-kernel_LPC55S06)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MM1")
    include(middleware_freertos-kernel_MIMX8MM6)
endif()
if(${MCUX_DEVICE} STREQUAL "K32L2B31A")
    include(middleware_freertos-kernel_K32L2B31A)
endif()
if(${MCUX_DEVICE} STREQUAL "MKE16Z4")
    include(middleware_freertos-kernel_MKE16Z4)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S06")
    include(middleware_freertos-kernel_LPC55S06)
endif()
if(${MCUX_DEVICE} STREQUAL "MKM14ZA5")
    include(middleware_freertos-kernel_MKM34ZA5)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54016")
    include(middleware_freertos-kernel_LPC54S018)
endif()
if(${MCUX_DEVICE} STREQUAL "MKV11Z7")
    include(middleware_freertos-kernel_MKV11Z7)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54018")
    include(middleware_freertos-kernel_LPC54S018)
endif()
if(${MCUX_DEVICE} STREQUAL "MKV31F51212")
    include(middleware_freertos-kernel_MKV31F51212)
endif()
if(${MCUX_DEVICE} STREQUAL "MKE12Z7")
    include(middleware_freertos-kernel_MKE17Z7)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54628")
    include(middleware_freertos-kernel_LPC54628)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5502CPXXXX")
    include(middleware_freertos-kernel_LPC5506CPXXXX)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MM5")
    include(middleware_freertos-kernel_MIMX8MM6)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5512")
    include(middleware_freertos-kernel_LPC55S16)
endif()
if(${MCUX_DEVICE} STREQUAL "MK22F51212")
    include(middleware_freertos-kernel_MK22F51212)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MM2")
    include(middleware_freertos-kernel_MIMX8MM6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8ML3")
    include(middleware_freertos-kernel_MIMX8ML8)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1173_cm4")
    include(middleware_freertos-kernel_MIMXRT1176_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1173_cm7")
    include(middleware_freertos-kernel_MIMXRT1176_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5516")
    include(middleware_freertos-kernel_LPC55S16)
endif()
if(${MCUX_DEVICE} STREQUAL "MKM34ZA5")
    include(middleware_freertos-kernel_MKM34ZA5)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54605")
    include(middleware_freertos-kernel_LPC54628)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1051")
    include(middleware_freertos-kernel_MIMXRT1052)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54618")
    include(middleware_freertos-kernel_LPC54628)
endif()
if(${MCUX_DEVICE} STREQUAL "MKE13Z7")
    include(middleware_freertos-kernel_MKE17Z7)
endif()
if(${MCUX_DEVICE} STREQUAL "MKE14Z7")
    include(middleware_freertos-kernel_MKE15Z7)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1021")
    include(middleware_freertos-kernel_MIMXRT1021)
endif()
if(${MCUX_DEVICE} STREQUAL "MKV10Z7")
    include(middleware_freertos-kernel_MKV11Z7)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MM3")
    include(middleware_freertos-kernel_MIMX8MM6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT555S_cm33")
    include(middleware_freertos-kernel_MIMXRT595S_cm33)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54018M")
    include(middleware_freertos-kernel_LPC54S018M)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5506")
    include(middleware_freertos-kernel_LPC55S06)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5514")
    include(middleware_freertos-kernel_LPC55S16)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S16")
    include(middleware_freertos-kernel_LPC55S16)
endif()
if(${MCUX_DEVICE} STREQUAL "K32L2B11A")
    include(middleware_freertos-kernel_K32L2B31A)
endif()
if(${MCUX_DEVICE} STREQUAL "MK02F12810")
    include(middleware_freertos-kernel_MK22F51212)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MQ7")
    include(middleware_freertos-kernel_MIMX8MQ6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1062")
    include(middleware_freertos-kernel_MIMXRT1062)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MN6")
    include(middleware_freertos-kernel_MIMX8MN6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8ML6")
    include(middleware_freertos-kernel_MIMX8ML8)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S018")
    include(middleware_freertos-kernel_LPC54S018)
endif()
if(${MCUX_DEVICE} STREQUAL "MKE15Z4")
    include(middleware_freertos-kernel_MKE16Z4)
endif()
if(${MCUX_DEVICE} STREQUAL "K32L3A60_cm0plus")
    include(middleware_freertos-kernel_K32L3A60_cm0plus)
endif()
if(${MCUX_DEVICE} STREQUAL "K32L3A60_cm4")
    include(middleware_freertos-kernel_K32L3A60_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1042")
    include(middleware_freertos-kernel_MIMXRT1042)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1176_cm4")
    include(middleware_freertos-kernel_MIMXRT1176_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1176_cm7")
    include(middleware_freertos-kernel_MIMXRT1176_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1175_cm4")
    include(middleware_freertos-kernel_MIMXRT1176_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1175_cm7")
    include(middleware_freertos-kernel_MIMXRT1176_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S018M")
    include(middleware_freertos-kernel_LPC54S018M)
endif()
if(${MCUX_DEVICE} STREQUAL "MK22F25612")
    include(middleware_freertos-kernel_MK22F51212)
endif()
if(${MCUX_DEVICE} STREQUAL "MKM35Z7")
    include(middleware_freertos-kernel_MKM35Z7)
endif()
if(${MCUX_DEVICE} STREQUAL "K32L2B21A")
    include(middleware_freertos-kernel_K32L2B31A)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC51U68")
    include(middleware_freertos-kernel_LPC51U68)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1061")
    include(middleware_freertos-kernel_MIMXRT1062)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MN2")
    include(middleware_freertos-kernel_MIMX8MN6)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5528")
    include(middleware_freertos-kernel_LPC55S28)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1165_cm4")
    include(middleware_freertos-kernel_MIMXRT1166_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1165_cm7")
    include(middleware_freertos-kernel_MIMXRT1166_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S66_cm33_core0")
    include(middleware_freertos-kernel_LPC55S69_cm33_core0)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S66_cm33_core1")
    include(middleware_freertos-kernel_LPC55S69_cm33_core1)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8ML4")
    include(middleware_freertos-kernel_MIMX8ML8)
endif()
if(${MCUX_DEVICE} STREQUAL "MKM34Z7")
    include(middleware_freertos-kernel_MKM34Z7)
endif()
if(${MCUX_DEVICE} STREQUAL "MKV31F12810")
    include(middleware_freertos-kernel_MKV31F51212)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MD6")
    include(middleware_freertos-kernel_MIMX8MQ6)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S005")
    include(middleware_freertos-kernel_LPC54S018)
endif()
if(${MCUX_DEVICE} STREQUAL "MKE17Z7")
    include(middleware_freertos-kernel_MKE17Z7)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1171_cm7")
    include(middleware_freertos-kernel_MIMXRT1176_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S69_cm33_core0")
    include(middleware_freertos-kernel_LPC55S69_cm33_core0)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S69_cm33_core1")
    include(middleware_freertos-kernel_LPC55S69_cm33_core1)
endif()
if(${MCUX_DEVICE} STREQUAL "K32L2A31A")
    include(middleware_freertos-kernel_K32L2A41A)
endif()
if(${MCUX_DEVICE} STREQUAL "MCIMX7U5")
    include(middleware_freertos-kernel_MCIMX7U5)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1024")
    include(middleware_freertos-kernel_MIMXRT1024)
endif()
if(${MCUX_DEVICE} STREQUAL "MKM33ZA5")
    include(middleware_freertos-kernel_MKM34ZA5)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1011")
    include(middleware_freertos-kernel_MIMXRT1011)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54005")
    include(middleware_freertos-kernel_LPC54S018)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MM4")
    include(middleware_freertos-kernel_MIMX8MM6)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S28")
    include(middleware_freertos-kernel_LPC55S28)
endif()
if(${MCUX_DEVICE} STREQUAL "MKE14Z4")
    include(middleware_freertos-kernel_MKE16Z4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MN1")
    include(middleware_freertos-kernel_MIMX8MN6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT533S_cm33")
    include(middleware_freertos-kernel_MIMXRT595S_cm33)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8ML8")
    include(middleware_freertos-kernel_MIMX8ML8)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S14")
    include(middleware_freertos-kernel_LPC55S16)
endif()
if(${MCUX_DEVICE} STREQUAL "MKV31F25612")
    include(middleware_freertos-kernel_MKV31F51212)
endif()
if(${MCUX_DEVICE} STREQUAL "MKV30F12810")
    include(middleware_freertos-kernel_MKV31F51212)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S26")
    include(middleware_freertos-kernel_LPC55S28)
endif()
if(${MCUX_DEVICE} STREQUAL "K32L2A41A")
    include(middleware_freertos-kernel_K32L2A41A)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5504")
    include(middleware_freertos-kernel_LPC55S06)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MN3")
    include(middleware_freertos-kernel_MIMX8MN6)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54608")
    include(middleware_freertos-kernel_LPC54628)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MD7")
    include(middleware_freertos-kernel_MIMX8MQ6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT685S_cm33")
    include(middleware_freertos-kernel_MIMXRT685S_cm33)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT595S_cm33")
    include(middleware_freertos-kernel_MIMXRT595S_cm33)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MQ5")
    include(middleware_freertos-kernel_MIMX8MQ6)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5502")
    include(middleware_freertos-kernel_LPC55S06)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1172_cm7")
    include(middleware_freertos-kernel_MIMXRT1176_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "MCIMX7U3")
    include(middleware_freertos-kernel_MCIMX7U5)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1015")
    include(middleware_freertos-kernel_MIMXRT1015)
endif()
if(${MCUX_DEVICE} STREQUAL "MK64F12")
    include(middleware_freertos-kernel_MK64F12)
endif()
if(${MCUX_DEVICE} STREQUAL "MK66F18")
    include(middleware_freertos-kernel_MK66F18)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54114_cm4")
    include(middleware_freertos-kernel_LPC54114_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8QM6_cm4_core0")
    include(middleware_freertos-kernel_MIMX8QM6_cm4_core0)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8QM6_cm4_core1")
    include(middleware_freertos-kernel_MIMX8QM6_cm4_core1)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8QX6")
    include(middleware_freertos-kernel_MIMX8QX6)
endif()
if(${MCUX_DEVICE} STREQUAL "MK28FA15")
    include(middleware_freertos-kernel_MK28FA15)
endif()
if(${MCUX_DEVICE} STREQUAL "MKL27Z644")
    include(middleware_freertos-kernel_MKL27Z644)
endif()

